### ISSUE TITLE
JS to TS Backend

### ISSUE THREAD

**Issue by crestonesoftware** [Crestone-Tech/travel-buddy#204]
[TypeScript react conversion guide](https://github.com/Microsoft/TypeScript-React-Conversion-Guide#typescript-react-conversion-guide)
[TypeScript with Apollo/GraphQL](https://www.apollographql.com/docs/react/development-testing/static-typing/)
- [ ] JS to TS Backend - POC/Research - how to approach the conversion
- [ ] JS to TS Backend - convert User (model, api, typedef, query)
- [ ] JS to TS Backend - convert User seeds 
- [ ] JS to TS Backend - convert Reservation (model, api, typedef, query)
- [ ] JS to TS Backend - convert Reservation User seeds 
- [ ] JS to TS Backend - convert Tribe (model, api, typedef, query)
- [ ] JS to TS Backend - convert Reservation User seeds
